spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store_reservation
    username: root

    password: # 비밀번호 노출로 인한 삭제
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create

  jwt:
    secret: iwantogoodeveloper


  openapi:
    secret: # api 키 노출로 인한 키 삭제